### ISSUE TITLE
doesn't seem to work

### ISSUE THREAD

**Issue by flux242** [rafaelmaiolla/diff-vscode#2]
no syntax colouring for diff files. Does the extension still work?

Visual Code
Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:00:46.854Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by rafaelmaiolla** [comment]
Yes, it still works.  Probably your theme doesn't support diff colorization.  Please change the theme to check.

**Comment by flux242** [comment]
indeed. I've patched the theme and now it's working
